In [ ]:
# ============================
# Course Summary: Python for Time Series Analysis and Forecasting
# ============================

# ----------------------------
# Foundational Python Libraries
# ----------------------------

# NumPy Basics:
# - Numerical processing and array manipulation

# Pandas Basics:
# - Data analysis and exploration

# Pandas Visualization:
# - Quick charting of time series data

# Pandas Time Series Tools:
# - Specialized methods for timestamped data

# ----------------------------
# Time Series Analysis
# ----------------------------

# Using Statsmodels:
# - Statistical analysis of time series data
# - Introduction to key metrics and visualization techniques

# ----------------------------
# Forecasting Models
# ----------------------------

# General Forecasting Models:
# - Focus on ARIMA (Autoregressive Integrated Moving Average) 
#   and variants like Seasonal ARIMA
# - Application of learned concepts: NumPy, Pandas, Statsmodels, Visualization

# Advanced Forecasting Models:
# - State-of-the-art methods including Recurrent Neural Networks (RNNs)
# - Facebook’s Prophet library for forecasting


---

In [2]:
# =====================================================
# Use Case: NumPy Vectorized Operations in Data Science
# =====================================================
# Scenario:
# Suppose we have a dataset of sales amounts in USD for 1 million transactions,
# and we want to apply a 10% tax to each transaction to calculate the total price.
# Doing this with Python lists and loops would be very slow for large datasets.
# NumPy allows us to perform this operation in a vectorized way, applying the
# calculation to the entire dataset at once without explicit loops.

import numpy as np

# Example dataset: 1 million transaction amounts
sales = np.random.uniform(low=10, high=1000, size=1_000_000)  # Array of floats

# Vectorized operation: apply 10% tax to all sales
total_with_tax = sales * 1.10  # Element-wise multiplication

# Benefits / Practicality in Data Science:
# 1. **Speed**: Vectorized operations use optimized C-level code, much faster than Python loops.
# 2. **Readability**: Single line of code replaces complex loops.
# 3. **Scalability**: Works efficiently with large datasets (millions of rows).
# 4. **Integration**: NumPy arrays can be easily used with Pandas, SciPy, and machine learning libraries.
#
# Example: Calculate total revenue
total_revenue = np.sum(total_with_tax)
print(f"Total Revenue (with tax): ${total_revenue:,.2f}")

# Summary:
# Using NumPy vectorized operations is practical in data science because it allows
# fast, concise, and scalable numerical computations on large datasets without loops.


Total Revenue (with tax): $554,833,931.75


---

In [4]:
# =====================================================
# Understanding 1D and 2D NumPy Arrays
# =====================================================

# ----------------------------
# 1D Array (One-Dimensional Array)
# ----------------------------
# - A single sequence of elements, has only one axis (dimension)
# - Think of it as a row of numbers
# - Example:

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Shape:", array_1d.shape)  # Output: (5,) → 5 elements along one axis

# ----------------------------
# 2D Array (Two-Dimensional Array / Matrix)
# ----------------------------
# - Like a table with rows and columns, has two axes (dimensions)
# - Think of it as a spreadsheet or matrix
# - Example:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("2D Array (Matrix):\n", array_2d)
print("Shape:", array_2d.shape)  # Output: (3, 3) → 3 rows and 3 columns

# ----------------------------
# Relevance to Data Science
# ----------------------------
# 1D arrays:
# - Represent single feature columns, vectors, or time series
# - Examples: daily temperatures, stock prices, salaries

# 2D arrays:
# - Represent structured datasets: rows = observations, columns = features
# - Example: Customer data
#     Rows: individual customers
#     Columns: age, income, purchase amount
# - Standard format for machine learning, statistical analysis, and data manipulation

# Key Points:
# - Understanding dimensions is crucial for vectorized operations and reshaping data
# - Proper dimensions are required when feeding data into ML models or data processing libraries


1D Array: [1 2 3 4 5]
Shape: (5,)
2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [9]:
# =====================================================
# Nested Lists and 2D NumPy Arrays
# =====================================================

# ----------------------------
# What is a Nested List?
# ----------------------------
# - A nested list is a Python list that contains other lists as its elements.
# - Each inner list represents a "row" when converting to a 2D NumPy array.
# - All inner lists should ideally have the same length to form a proper matrix.

# Example of a nested list:
nested_list = [
    [1, 2, 3],  # Row 1
    [4, 5, 6],  # Row 2
    [7, 8, 9]   # Row 3
]

# ----------------------------
# Converting Nested List to 2D NumPy Array
# ----------------------------
import numpy as np

array_2d = np.array(nested_list)  # Convert nested list to 2D array (matrix)

print("2D Array (Matrix):")
print(array_2d)
print("Shape (rows, columns):", array_2d.shape)  # Returns (3, 3)
print("Total elements:", array_2d.size)           # Returns 9

# ----------------------------
# Key Points / Relevance to Data Science
# ----------------------------
# 1. Each inner list becomes a row in the 2D array.
# 2. Useful for structured/tabular data: rows = observations, columns = features.
# 3. Once converted to a NumPy array, vectorized operations can be applied efficiently.
# 4. Typical workflow: raw nested Python lists → 2D NumPy array → Pandas DataFrame → ML / analysis.


2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape (rows, columns): (3, 3)
Total elements: 9


---

In [10]:
# =====================================================
# 1. Creating NumPy Arrays
# =====================================================

# Step 1: Import NumPy
import numpy as np

# Step 2: Convert a single Python list to a 1D NumPy array
my_list = [1, 2, 3]
array_1d = np.array(my_list)  # Convert list to 1D array

print("1D Array:")
print(array_1d)
print("Type:", type(array_1d))
print("Shape (dimensions):", array_1d.shape)  # Shape of the array (number of elements along each axis)
print("Total elements:", array_1d.size)       # Total number of elements in the array
print()

# Step 3: Convert a nested Python list to a 2D NumPy array (matrix)
nested_list = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]

array_2d = np.array(nested_list)  # Convert nested list to 2D array

print("2D Array (Matrix):")
print(array_2d)
print("Type:", type(array_2d))
print("Shape (rows, columns):", array_2d.shape)  # Shape of the array (rows, columns)
print("Total elements:", array_2d.size)           # Total number of elements in the array

# ----------------------------
# Notes:
# ----------------------------
# - 1D array: single sequence of elements (one axis)
#   Useful for single feature vectors or time series.
# - 2D array: table/matrix with rows and columns (two axes)
#   Useful for structured datasets: rows = observations, columns = features.
# - .shape returns dimensions: (elements,) for 1D, (rows, columns) for 2D.
# - .size returns the total number of elements in the array.

1D Array:
[1 2 3]
Type: <class 'numpy.ndarray'>
Shape (dimensions): (3,)
Total elements: 3

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>
Shape (rows, columns): (3, 3)
Total elements: 9


----

In [ ]:
# =====================================================
# 2. Built-in NumPy Array Creation Methods
# =====================================================

# ----------------------------
# 1. np.arange(start, stop, step)
# ----------------------------
# - Similar to Python's built-in range(), but returns a NumPy array
# - Creates values from 'start' up to but NOT including 'stop', with optional 'step'
arr_arange = np.arange(0, 10, 2)  # Start=0, Stop=10, Step=2
print("np.arange(0,10,2):", arr_arange)
# Output: [0 2 4 6 8]

# ----------------------------
# 2. np.zeros(shape) and np.ones(shape)
# ----------------------------
# - np.zeros(shape): creates an array filled with zeros
# - np.ones(shape): creates an array filled with ones
zeros_1d = np.zeros(5)          # 1D array of 5 zeros
ones_2d = np.ones((3, 4))       # 2D array (3 rows x 4 columns) of ones

print("1D Zeros:", zeros_1d)
print("2D Ones:\n", ones_2d)

# ----------------------------
# 3. np.linspace(start, stop, num)
# ----------------------------
# - Creates 'num' evenly spaced numbers between start and stop (inclusive)
linspace_arr = np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
print("np.linspace(0,10,5):", linspace_arr)
# Output: [ 0.   2.5  5.   7.5 10. ]

# ----------------------------
# 4. np.eye(n)
# ----------------------------
# - Creates an identity matrix (square matrix with 1s on the diagonal)
identity_matrix = np.eye(4)  # 4x4 identity matrix
print("4x4 Identity Matrix:\n", identity_matrix)

# ----------------------------
# 5. np.random
# ----------------------------
# - Used to create arrays of random numbers for testing, simulation, or sampling
# - Examples:
rand_uniform = np.random.rand(5)          # 5 random numbers between 0 and 1
rand_normal = np.random.randn(3, 3)       # 3x3 array from standard normal distribution
print("Random Uniform Array:", rand_uniform)
print("Random Normal 3x3 Array:\n", rand_normal)

# =====================================================
# 🧠 Understanding np.random.randn(3, 3)
# =====================================================
# 1. What it does:
# -----------------------------------------------------
# np.random.randn(3, 3) creates a 3×3 NumPy array filled 
# with random numbers drawn from a standard normal distribution 
# (also called a Gaussian distribution).
#
# Example:
# rand_normal = np.random.randn(3, 3)
#
# Output:
# array([[ 0.4967, -0.1383,  0.6477],
#        [ 1.5230, -0.2341, -0.2341],
#        [ 0.5425, -0.4695,  0.2419]])
#
# -----------------------------------------------------
# 2. What is a Standard Normal Distribution?
# -----------------------------------------------------
# A special kind of bell-shaped curve where:
#   - Mean (μ) = 0
#   - Standard deviation (σ) = 1
#
# Meaning:
#   - Most values are close to 0
#   - Some values slightly above or below 0
#   - Few values far away (like −3 or +3)
#
# Visual representation:
#             .
#           .   .
#         .       .
# ----.----.----.----.----.---->
#    -3   -2    0    2    3
#        mean=0, std=1
#
# So when np.random.randn() is called, NumPy generates random
# numbers centered around zero, following this bell-shaped pattern.
#
# -----------------------------------------------------
# 3. Parameters Explained:
# -----------------------------------------------------
# Syntax: np.random.randn(d1, d2, ...)
#   - d1, d2, ... → dimensions (shape) of the array
#   - (3, 3) means 3 rows × 3 columns
#
# Example:
# np.random.randn(3, 3)
# → Creates a 3x3 matrix of random values
#
# Note: Each number changes every time unless a random seed
#       is set using np.random.seed().
#
# -----------------------------------------------------
# 4. Why It’s Useful in Data Science:
# -----------------------------------------------------
# ✅ Testing algorithms → Create synthetic data with realistic variation
# ✅ Simulations → Model uncertainty or add random noise
# ✅ Machine Learning → Initialize model weights randomly 
#                       using normal distribution
#
# Summary:
# np.random.randn() = standard normal data generator
# - Centered around 0
# - Useful for data simulation, modeling, and ML initialization
# =====================================================


# ----------------------------
# Key Points / Relevance to Data Science
# ----------------------------
# - np.arange and np.linspace: useful for creating sequences or time indices
# - np.zeros and np.ones: often used to initialize arrays or matrices
# - np.eye: important in linear algebra and machine learning (e.g., identity matrices)
# - np.random: simulate data, test algorithms, generate synthetic datasets
# - These methods allow fast and memory-efficient creation of arrays without manual loops


np.arange(0,10,2): [0 2 4 6 8]
1D Zeros: [0. 0. 0. 0. 0.]
2D Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
np.linspace(0,10,5): [ 0.   2.5  5.   7.5 10. ]
4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random Uniform Array: [0.5328068  0.98626208 0.27018522 0.53064004 0.82560671]
Random Normal 3x3 Array:
 [[-1.09359735 -1.71139305  0.30126732]
 [-0.03343938  1.24767532  0.31803825]
 [-0.27203496  1.44038017 -1.24831124]]


---

In [ ]:
# =====================================================
# np.linspace(start, stop, num)
# =====================================================
# - Creates 'num' evenly spaced numbers between 'start' and 'stop' (inclusive)
# - Unlike np.arange, you specify the number of points, not the step size
# - Useful for generating sequences, time intervals, or grids for plotting

import numpy as np

# Example: 5 numbers from 0 to 10
linspace_arr = np.linspace(0, 10, 5)
print("np.linspace(0,10,5):", linspace_arr)
# Output: [ 0.   2.5  5.   7.5 10. ]

# ----------------------------
# Explanation:
# ----------------------------
# Number of points (num) = 5
# Start = 0, Stop = 10
# Step size is automatically calculated as:
# step = (stop - start) / (num - 1) = (10 - 0) / (5 - 1) = 2.5
# So the sequence becomes:
# 0, 0+2.5=2.5, 2.5+2.5=5.0, 5.0+2.5=7.5, 7.5+2.5=10

# ----------------------------
# Key Points / Relevance to Data Science
# ----------------------------
# - Always includes the stop value by default
# - Step size is auto-calculated based on number of points
# - Commonly used for:
#   - Generating evenly spaced time intervals
#   - Creating grids for plotting or simulations
#   - Interpolating data points


---

In [ ]:
# =====================================================
# NumPy Random Number Generation: rand vs randn
# =====================================================

# ----------------------------
# 1. np.random.rand()
# ----------------------------
# - Generates random numbers from a uniform distribution
# - All numbers are between 0 (inclusive) and 1 (exclusive)
# - Can specify shape (1D, 2D, etc.)
rand_uniform = np.random.rand(5)      # 1D array of 5 random numbers between 0 and 1
rand_uniform_2d = np.random.rand(2, 3) # 2x3 array

print("Random Uniform 1D Array:", rand_uniform)
print("Random Uniform 2D Array:\n", rand_uniform_2d)

# ----------------------------
# 2. np.random.randn()
# ----------------------------
# - Generates random numbers from the standard normal distribution (Gaussian)
# - Mean = 0, Standard Deviation = 1
# - Numbers can be positive or negative
# - Can specify shape (1D, 2D, etc.)
rand_normal = np.random.randn(3, 3)  # 3x3 array
print("Random Normal 3x3 Array:\n", rand_normal)

# ----------------------------
# Key Differences:
# ----------------------------
# Function       | Distribution Type | Range
# -------------- | ---------------- | ----------------------
# np.random.rand | Uniform           | 0 <= x < 1
# np.random.randn| Standard Normal   | -∞ < x < ∞ (most values ~[-3,3])
# ----------------------------
# Notes:
# - Use rand() when you want evenly distributed numbers between 0 and 1.
# - Use randn() when you want numbers with a normal distribution centered at 0.
# - Both functions are widely used in simulations, testing algorithms, and generating synthetic datasets.


In [ ]:
# =================================================================
# Understanding np.random.randn() and Standard Normal Distribution
# ================================================================

# Generate a 3x3 array of random numbers from standard normal distribution
rand_normal = np.random.randn(3, 3)

print("Random Normal 3x3 Array:\n", rand_normal)
print("Array Shape (dimensions):", rand_normal.shape)  # 3 rows x 3 columns
print("Total Elements:", rand_normal.size)             # 9 elements

# ----------------------------
# Key Points:
# ----------------------------
# - Standard normal distribution: mean (μ) = 0, standard deviation (σ) = 1
# - Most numbers fall within:
#     1σ → -1 to 1  (~68% of values)
#     2σ → -2 to 2  (~95% of values)
#     3σ → -3 to 3  (~99.7% of values)
# - Values can be negative or positive
# - Array dimensions (shape) = (3,3) → 3 rows and 3 columns
# - Total elements = 9
# - Occasionally, numbers slightly outside [-3,3] may appear, as the distribution is unbounded


---

In [ ]:
# =====================================================
# Random Numbers, Seeding, and Array Methods
# =====================================================

# ----------------------------
# Random Number Generation
# ----------------------------

# 1. Uniform random numbers between 0 and 1
rand_single = np.random.rand(1)        # Single random number
rand_multiple = np.random.rand(4)      # 4 random numbers
rand_matrix = np.random.rand(5, 5)     # 5x5 array of random numbers

# 2. Standard normal distribution (mean=0, std=1)
randn_single = np.random.randn(1)      # Single number
randn_matrix = np.random.randn(3, 3)   # 3x3 array of numbers from standard normal

# 3. Normal distribution with custom mean and std
rand_normal_custom = np.random.normal(loc=10, scale=2, size=(2, 3))  # 2x3 array

# 4. Random integers
rand_int_single = np.random.randint(low=1, high=100)       # Single integer between 1-99
rand_int_array = np.random.randint(low=1, high=100, size=10)  # Array of 10 integers

# ----------------------------
# Setting a Seed for Reproducibility
# ----------------------------
# - Setting a seed ensures that the same random numbers are generated each time
np.random.seed(42)
rand_seeded = np.random.rand(4)  # Same 4 numbers every time seed=42 is used

# ----------------------------
# Array Attributes and Methods
# ----------------------------

# 1. Reshape
arr = np.arange(25)              # 1D array from 0 to 24
reshaped_arr = arr.reshape(5, 5) # Reshape to 5 rows x 5 columns
# Note: Total number of elements must match (25 elements → 5x5)

# 2. Max, Min
random_array = np.random.randint(0, 50, size=10)
max_value = random_array.max()   # Maximum value
min_value = random_array.min()   # Minimum value

# 3. Argmax, Argmin
max_index = random_array.argmax()  # Index of maximum value
min_index = random_array.argmin()  # Index of minimum value

# 4. dtype
array_type = random_array.dtype     # Data type of elements (e.g., int32, float64)

# ----------------------------
# Key Points / Relevance to Data Science
# ----------------------------
# - np.random.rand, np.random.randn: useful for simulating data or testing algorithms
# - np.random.randint: generate discrete random samples for simulations or tests
# - Setting a seed allows reproducible results for experiments or debugging
# - .reshape: convert arrays to required dimensions for ML models or computations
# - .max, .min, .argmax, .argmin: quick insights on data, feature engineering
# - .dtype: understand precision and type of numerical data (important for memory and calculations)


In [ ]:
# =====================================================
# np.random.normal(loc=0.0, scale=1.0, size=None)
# =====================================================
# - Generates random numbers from a normal (Gaussian) distribution
# - Useful for simulating data, testing models, or creating synthetic datasets

# ----------------------------
# Parameters
# ----------------------------
# loc   : float, mean (μ) of the distribution (center of the bell curve)
# scale : float, standard deviation (σ) of the distribution (spread of values)
# size  : int or tuple of ints, output shape of the array
#         - int -> 1D array of that length
#         - tuple -> multi-dimensional array with specified shape

# ----------------------------
# Example: 2x3 array from normal distribution
# ----------------------------
rand_normal_custom = np.random.normal(loc=10, scale=2, size=(2, 3))
print("Random Normal Array (mean=10, std=2, shape=2x3):\n", rand_normal_custom)

# Sample Output (will vary unless a seed is set):
# [[11.2,  9.5, 12.1],
#  [10.3,  7.8, 10.9]]

# ----------------------------
# Key Points
# ----------------------------
# - Numbers are centered around 'loc' (mean)
# - Most values fall within approximately loc ± scale
# - Setting 'size' allows creation of multi-dimensional arrays for simulations
# - Setting a seed (np.random.seed()) ensures reproducible random numbers


In [ ]:
# =====================================================
# np.random.seed(seed_number)
# =====================================================
# - Think of a magic number machine that gives random numbers
# - Normally, every press gives different numbers
# - .seed() is like telling the machine:
#     "Start at this specific page of your number book"
# - Using the same seed = always get the same numbers
# - Not setting a seed = random numbers change every time

# ----------------------------
# Example
# ----------------------------
np.random.seed(42)          # Start at "page 42" in the number book
numbers = np.random.rand(4) # Press the button 4 times → same 4 numbers every time
print("Random numbers with seed 42:", numbers)

# Output (always same with seed 42):
# [0.37454012 0.95071431 0.73199394 0.59865848]

# ----------------------------
# Key Points
# ----------------------------
# - Resetting the seed restarts the sequence
# - Useful for reproducibility in experiments, simulations, or tests
# - Without seed, numbers will be different each time


In [3]:
# =====================================================
# NumPy Array: max, min, argmax, argmin
# =====================================================
# - Useful for quickly finding the largest/smallest values
#   and their positions in an array
# - Works with 1D, 2D, or higher-dimensional arrays
# - Can specify axis for row-wise or column-wise operations

# ----------------------------
# Create a random array
# ----------------------------
# Create an array of 10 random integers between 0 and 49
random_array = np.random.randint(0, 50, size=10)
print("Random Array:", random_array)

# ----------------------------
# Max and Min values
# ----------------------------
max_value = random_array.max()  # Largest value in the array
min_value = random_array.min()  # Smallest value in the array
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)

# ----------------------------
# Index of Max and Min values
# ----------------------------
max_index = random_array.argmax()  # Position of largest value
min_index = random_array.argmin()  # Position of smallest value
print("Index of Maximum Value:", max_index)
print("Index of Minimum Value:", min_index)

# ----------------------------
# Example with 2D array
# ----------------------------
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Max of each column:", matrix.max(axis=0))  # Column-wise max → [4 5 6]
print("Max of each row:", matrix.max(axis=1))     # Row-wise max    → [3 6]
print("Index of max in flattened array:", matrix.argmax())  # Flattened index → 5


Random Array: [40  9 26 24 38 39 25 33  7 28]
Maximum Value: 40
Minimum Value: 7
Index of Maximum Value: 0
Index of Minimum Value: 8
Max of each column: [4 5 6]
Max of each row: [3 6]
Index of max in flattened array: 5


In [22]:
# =====================================================
# NumPy Array: max, min, argmax, argmin
# =====================================================
# - max()  → Returns the largest value in the array
# - min()  → Returns the smallest value in the array
# - argmax() → Returns the index (position) of the largest value
# - argmin() → Returns the index (position) of the smallest value
# - Useful for:
#     - Quickly summarizing data
#     - Finding extreme values
#     - Outlier detection
#     - Feature engineering
# - Works on 1D, 2D, or higher-dimensional arrays
# - axis parameter allows row-wise or column-wise computation

# ----------------------------
# Example: 1D Array
# ----------------------------
random_array = np.array([23, 7, 45, 12, 30, 18, 3, 28, 14, 41])
print("Random Array:", random_array)

# Max and Min values
max_value = random_array.max()   # 45
min_value = random_array.min()   # 3

# Index of Max and Min values
max_index = random_array.argmax()  # 2 (position of 45)
min_index = random_array.argmin()  # 6 (position of 3)

print("Maximum Value:", max_value)
print("Minimum Value:", min_value)
print("Index of Maximum Value:", max_index)
print("Index of Minimum Value:", min_index)

# ----------------------------
# Illustration:
# ----------------------------
# Array positions:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Array values:     [23, 7, 45, 12, 30, 18, 3, 28, 14, 41]
# max() value = 45 at index 2
# min() value = 3  at index 6

# ----------------------------
# Example: 2D Array
# ----------------------------
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Flattened max/min
flat_max_index = matrix.argmax()  # 5 → value 6
flat_min_index = matrix.argmin()  # 0 → value 1

# Column-wise max/min
col_max_index = matrix.argmax(axis=0)  # Max in each column → [1 1 1]
col_min_index = matrix.argmin(axis=0)  # Min in each column → [0 0 0]

# Row-wise max/min
row_max_index = matrix.argmax(axis=1)  # Max in each row → [2 2]
row_min_index = matrix.argmin(axis=1)  # Min in each row → [0 0]

print("Flattened Max Index:", flat_max_index)
print("Flattened Min Index:", flat_min_index)
print("Column-wise Max Index:", col_max_index)
print("Row-wise Max Index:", row_max_index)


Random Array: [23  7 45 12 30 18  3 28 14 41]
Maximum Value: 45
Minimum Value: 3
Index of Maximum Value: 2
Index of Minimum Value: 6
Flattened Max Index: 5
Flattened Min Index: 0
Column-wise Max Index: [1 1 1]
Row-wise Max Index: [2 2]


In [ ]:
# =====================================================
# Understanding axis in 2D NumPy arrays with argmax/argmin
# =====================================================
# We have this 2D array:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Step 1: Understand axis in NumPy
# - axis=0 → along the rows → "look down each column"
# - axis=1 → along the columns → "look across each row"

# Think of it like this:
#        Col0  Col1  Col2
# Row0     1     2     3
# Row1     4     5     6

# Step 2: argmax(axis=0)
# - Looks down each column
# - Returns the index of the largest value in each column (row index)
# Column by column:
# Col0: [1,4] → max=4 → index 1
# Col1: [2,5] → max=5 → index 1
# Col2: [3,6] → max=6 → index 1
col_max_index = matrix.argmax(axis=0)  # Result: [1, 1, 1]
# Note: These are row indices of the max in each column

# Step 3: argmin(axis=0) (for comparison)
# - Looks down each column
# - Returns the index of the smallest value in each column (row index)
# Col0: [1,4] → min=1 → index 0
# Col1: [2,5] → min=2 → index 0
# Col2: [3,6] → min=3 → index 0
col_min_index = matrix.argmin(axis=0)  # Result: [0, 0, 0]

# Step 4: Why this matters
# - When working with 2D data (like spreadsheets), we often want max/min per column or per row
# - axis=0 → column-wise, axis=1 → row-wise
# - argmax / argmin gives the **position** of these values, useful for locating extremes
#   or for indexing other arrays


---